name: tests.yaml

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      CI: 1
      PYTHONWARNINGS: error
      NUM_JOBS: 4

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Setup Python and Dependencies
      run: |
        sudo apt update
        pip install -r requirements.txt

    - name: Build openpilot
      run: |
        scons -j$(nproc)

    - name: Static analysis
      run: |
        tools/op.sh lint

    - name: Run unit tests
      run: |
        pytest --maxfail=1 --disable-warnings

    - name: Run all integration tests
      run: |
        pytest -m "not slow"
